<a href="https://colab.research.google.com/github/Eriau/itii-seance7/blob/master/Seance7Answers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

En utilisant numpy:

Ex 1 :Addition
Écrire un programme pour lire les éléments de deux matrices et ajoutez les deux matrices dans la troisième.

La somme de deux matrices de taille (m,n), $(A_{ij}) et (B_{ij}) notée $A+B$  est à nouveau une matrice (C_{ij}) de taille (m,n), obtenue en additionnant les éléments correspondants: $c_{ij}=a_{ij}+b_{ij}$


In [ ]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Une matrice
b = np.array([[9,8,7],[6,5,4],[3,2,1]])

def sommeAfficheMats(matUn, matDeux):
  if matUn.shape == matDeux.shape :
    matTrois = matUn + matDeux
    print("{0}+{1}={2}".format(matUn,matDeux,matTrois))
  else :
    print("Pas les bonnes dimensions")

sommeAfficheMats(a, b) # Pas ouf l'affichage

[[1 2 3]
 [4 5 6]
 [7 8 9]]+[[9 8 7]
 [6 5 4]
 [3 2 1]]=[[10 10 10]
 [10 10 10]
 [10 10 10]]


Ex2 :Multiplication
Écrire un programme pour lire les éléments de deux matrices, puis multipliez les deux matrices dans la troisième.

Deux matrices ne peuvent être multipliées que si le nombre de colonnes de la première matrice est le même que le nombre de lignes de la seconde matrice.

Si $ A=(a_{ij})$ est une matrice de taille (m,n), $ B=(b_{ij})$ et est une matrice de taille (n,p), alors leur produit, noté $AB=(c_{ij})$ est une matrice de taille (m,p) définie par :
$$\forall i,j : c_{ij}=\sum_{k=i}^{n} a_{ik}*b_{kj}$$

In [ ]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Une matrice
b = np.array([[9,8,7],[6,5,4],[3,2,1]])

def produitAfficheMats(matUn, matDeux):
  if matUn.shape[1] == matDeux.shape[0] :
    matTrois = np.dot(matUn,matDeux)
    print("{0}*{1}={2}".format(matUn,matDeux,matTrois))
  else :
    print("Pas les bonnes dimensions")

produitAfficheMats(a, b) # Pas ouf l'affichage

[[1 2 3]
 [4 5 6]
 [7 8 9]]*[[9 8 7]
 [6 5 4]
 [3 2 1]]=[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


Ex 3: Matrice de Markov

Une matrice de Markov est une matrice carrée dont chaque élément est un réel compris entre 0 et 1 et dont la somme des éléments de chaque ligne vaut 1. Cela correspond, en probabilité, à la matrice de transition d'une chaîne de Markov finie.

Une matrice est dite bistochastique (ou doublement stochastique) si la somme des éléments de chaque ligne et de chaque colonne vaut 1.

1. Ecrire une fonction eststochastique(P) qui permet de vérifier est ce que la matrice P est stochastique ou non
2. Ecrire une fonction estbistochastique(P) qui permet de vérifier est ce que la matrice P est bistochastique ou non
3. Ecrire une fonction vecteurstable(G, h) qui permet de vérifier est ce que h est un vecteur stable de G ou non



In [ ]:
import numpy as np

# Faudrait vérifier que c'est égal à un avec une certaine précision

# 1

def estStochastique(P):
  numLigne = P.shape[0]
  numCol = P.shape[1]

  etat = False # On suppose la matrice non stochastique

  for i in range numLigne :
    sum = 0
    for j in range numCol :
      s += P[i][j]
    if abs(((s - 1)/s) < 1e-6)) :
        etat = True  
    elif s > 1 :
      etat = False
      break
  return etat 

# 2

def estBistochastique(P):
  numLigne = P.shape[0]
  numCol = P.shape[1]

  etat = False # On suppose la matrice non bistochastique

  if estStochastique(P):
    for i in range numCol :
      sum = 0
      for j in range numLigne :
        s += P[i][j]
      if abs(((s - 1)/s) < 1e-6)) :
        etat = True
      elif s > 1 :
        etat = False
        break
  else:
    etat = False
  return etat 

# 3

def vecteurStable(G, h):
  numLigne = G.shape[0]
  numCol = G.shape[1]

  etat = True # On suppose que h est un vecteur stable de G

  if estStochastique(G) :
    for j in range numCol :
      s = 0
      for i in range numLigne :
        s += h[i]*G[i][j]
      if s != h[j] :
        etat = False
    return Etat

Ex 4: Transposer

Programmer une fonction qui, étant donné une matrice à deux dimensions A, retourne lamatrice B dont la première colonne est la première ligne de A, la seconde la deuxième ligne de A, etc. B s’appelle la transposée de A.

In [ ]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Une matrice

def transp(mat):
  matTransp = mat.T
  return matTransp

b = transp(a)
print(b)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Ex 5: Permutations
1. $M$ désignant une matrice quelconque d’entiers à $l_i$ lignes et $co$ colonnes, $n$ un entier quelconque, programmer une fonction qui retourne la matrice $Sortie$ qui empile verticalement les $co+1$ matrices obtenues en adjoignant à $M$ une colonne $A$ à $li$ lignes dont tousles éléments sont égaux à $n$, $A$ étant placée d’abord devant $M$, puis entre la première et deuxième colonne de $M^a$,etc, jusqu’à ce que $A$ devienne sa dernière colonne. La matriceobtenue  aura $co+1$ colonnes et $(n+1)$ $li$ lignes

2. Écrire toutes les permutations de(1, ..., n)

In [ ]:
# appliquer une permutation
def apply_permutation(A,perm,N):
    B=np.empty_like(A) # A est une matrice NxN d'entiers dans range(N)
    for i in range(N):
            B[A[:]==i]=perm[i] # perm est une permutation de range(N)
    return B